name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools git unzip openjdk-11-jdk build-essential \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev wget

    - name: Install Buildozer & Cython
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cython buildozer

    - name: Install Android SDK & Build Tools
      run: |
        mkdir -p $HOME/Android/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/Android/cmdline-tools
        yes | $HOME/Android/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
        echo "export ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV
        echo "export PATH=$PATH:$HOME/Android/cmdline-tools/cmdline-tools/bin:$HOME/Android/platform-tools:$HOME/Android/build-tools/33.0.2" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: buildozer init

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: myapp-apk
        path: bin/*.apk
